casbin/jcasbin

src/main/java/org/casbin/jcasbin/util/Util.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java

This is a fix for the escapeAssertion Bug, discussed here: https://github.com/casbin/casbin/issues/192
I also implemented the removeComments Method.

Fixed escape assertion bug & implemented comment removing

---

src/main/java/org/casbin/jcasbin/persist/file_adapter/FileAdapter.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

implement load policy by inputStream

implement load policy by inputStream

---

src/main/java/org/casbin/jcasbin/main/InternalEnforcer.java

Join the cache after persisting the policy

Join the cache after persisting the policy

---

src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/test/java/org/casbin/jcasbin/main/SyncedEnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/SyncedRbacAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/SyncedRbacAPIWithDomainsUnitTest.java

Fixes #30 SyncedEnforcer

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

Add validation on param size for enforce method

---

src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/test/java/org/casbin/jcasbin/main/RbacAPIWithDomainsUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/49

Add getImplicitPermissionsForUserInDomain()

---

src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

Performance improvement in BuiltInFunctions
- moved compile pattern out of keyMatch2 and keyMatch3

Performance improvement in BuiltInFunctions

---

src/main/java/org/casbin/jcasbin/config/Config.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/test/java/org/casbin/jcasbin/main/SyncedManagementAPIUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/60

Added missing functions in Synced Enforcer.

---

src/main/java/org/casbin/jcasbin/main/InternalEnforcer.java

If doesn't check would be cause to duplicate additions.

fix: add duplicate check

---

.editorconfig
src/main/java/org/casbin/jcasbin/main/Enforcer.java

Fix: https://github.com/casbin/jcasbin/issues/69

:bug: NullPointerException at hasRoleForUser

---

pom.xml
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkABACModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkBasicModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkKeyMatchModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkPriorityModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelLarge.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelMedium.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelSingle.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelSmall.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithDeny.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithDomains.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithResourceRoles.java

Fix: https://github.com/casbin/jcasbin/issues/73

Add some benchmarks.

---

examples/abac_rule_model.conf
examples/abac_rule_policy.csv
examples/abac_rule_with_domains_model.conf
examples/abac_rule_with_domains_policy.csv
pom.xml
src/main/java/org/casbin/jcasbin/model/FunctionMap.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/Util.java
src/main/java/org/casbin/jcasbin/util/function/EvalFunc.java
src/test/java/org/casbin/jcasbin/main/AbacAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java

Fix: #84 
Added eval() feature to jCasbin. Added corresponding test cases.

Added eval() feature to jCasbin. Added corresponding test cases.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/InternalEnforcer.java
src/main/java/org/casbin/jcasbin/main/ManagementEnforcer.java
src/main/java/org/casbin/jcasbin/model/Assertion.java
src/main/java/org/casbin/jcasbin/model/Model.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/main/java/org/casbin/jcasbin/persist/BatchAdapter.java
src/main/java/org/casbin/jcasbin/persist/WatcherEx.java
src/main/java/org/casbin/jcasbin/rbac/DefaultRoleManager.java

Modify adapter policies before modifying memory

---

examples/keymatch4_model.conf
examples/keymatch4_policy.csv
src/main/java/org/casbin/jcasbin/model/FunctionMap.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/function/KeyMatch3Func.java
src/main/java/org/casbin/jcasbin/util/function/KeyMatch4Func.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

Added keyMatch3 and keyMatch4 function. Added corresponding test cases.

---

examples/rbac_with_all_pattern_model.conf
examples/rbac_with_all_pattern_policy.csv
examples/rbac_with_domain_pattern_model.conf
examples/rbac_with_domain_pattern_policy.csv
examples/rbac_with_pattern_model.conf
examples/rbac_with_pattern_policy.csv
src/main/java/org/casbin/jcasbin/rbac/DefaultRoleManager.java
src/main/java/org/casbin/jcasbin/rbac/DomainRoles.java
src/main/java/org/casbin/jcasbin/rbac/Role.java
src/main/java/org/casbin/jcasbin/rbac/RoleManager.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java
src/test/java/org/casbin/jcasbin/main/RbacAPIWithPatternMatchUnitTest.java

This PR is a port of casbin support for pattern functions in g.
Also a few refactoring following sonar advices in BuiltInFunctions.
Waiting for your review,
thanks.

Porting casbin support for pattern functions in g (1st arg and domain)

---

examples/multiline_model.conf
examples/multiline_policy.csv
src/main/java/org/casbin/jcasbin/config/Config.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

Added multiline text support for loading model files.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java

syncedEnforcer.enforce() now using read lock.

---

src/main/java/org/casbin/jcasbin/main/InternalEnforcer.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/main/java/org/casbin/jcasbin/rbac/DefaultRoleManager.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

Fix: #100 
Signed-off-by: tldyl <756560020@qq.com>

Fixed the javadoc error.

---

src/main/java/org/casbin/jcasbin/persist/FilteredAdapter.java
src/main/java/org/casbin/jcasbin/persist/file_adapter/FilteredAdapter.java

Extracted out the interface for FilteredAdapter in Java like how we did in Golang。
Fix: https://github.com/casbin/jcasbin/issues/107

Add the FilteredAdapter interface.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/persist/Dispatcher.java

extract the "add Dispatcher" PR from the code in PR: #111。

add Dispatcher.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/main/InternalEnforcer.java
src/main/java/org/casbin/jcasbin/main/ManagementEnforcer.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/main/java/org/casbin/jcasbin/persist/Dispatcher.java
src/main/java/org/casbin/jcasbin/persist/UpdatableAdapter.java
src/main/java/org/casbin/jcasbin/persist/WatcherUpdatable.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/ManagementAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/SyncedRbacAPIUnitTest.java

add UpdatableAdapter.

---

src/main/java/org/casbin/jcasbin/persist/BatchAdapter.java
src/main/java/org/casbin/jcasbin/persist/FilteredAdapter.java
src/main/java/org/casbin/jcasbin/persist/WatcherEx.java
src/main/java/org/casbin/jcasbin/persist/file_adapter/FilteredAdapter.java
src/main/java/org/casbin/jcasbin/rbac/DomainRoles.java
src/main/java/org/casbin/jcasbin/rbac/Role.java
src/main/java/org/casbin/jcasbin/util/function/EvalFunc.java
src/main/java/org/casbin/jcasbin/util/function/KeyMatch4Func.java
src/test/java/org/casbin/jcasbin/main/AbacAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/FilteredAdapterTest.java
src/test/java/org/casbin/jcasbin/main/GroupRoleManagerTest.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkABACModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkBasicModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkKeyMatchModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkPriorityModel.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelLarge.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelMedium.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelSingle.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelSmall.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithDeny.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithDomains.java
src/test/java/org/casbin/jcasbin/main/benchmark/BenchmarkRBACModelWithResourceRoles.java

Fix: https://github.com/casbin/jcasbin/issues/119

Add missing license headers

---

src/main/java/org/casbin/jcasbin/main/DistributedEnforcer.java
src/test/java/org/casbin/jcasbin/main/SyncedDistributedAPIUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/117

Add DistributedEnforcer.

---

examples/glob_model.conf
examples/glob_policy.csv
src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/model/FunctionMap.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/Glob.java
src/main/java/org/casbin/jcasbin/util/function/GlobMatchFunc.java
src/test/java/org/casbin/jcasbin/main/BuiltInFunctionsUnitTest.java
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/121

Add globMatch pattern.

---

.travis.yml

Fix: https://github.com/casbin/jcasbin/issues/76

Modify the file named ".travis.yml" that'll run maven-semantic-release after success.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java

Fix: https://github.com/casbin/jcasbin/issues/128

Fix the loadFilteredPolicy.

---

.travis.yml
maven-settings.xml

Fix: https://github.com/casbin/jcasbin/issues/130

Fix the travis ci.

---

.github/semantic.yml
src/main/java/org/casbin/jcasbin/model/FunctionMap.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/function/KeyGet2Func.java
src/main/java/org/casbin/jcasbin/util/function/KeyGetFunc.java
src/test/java/org/casbin/jcasbin/main/BuiltInFunctionsUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

feat: add keyGet and keyGet2 functions.

---

README.md
pom.xml

Fix: #134 
Test the sematic-release.

fix: update the pom.xml

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java

Fix: https://github.com/casbin/jcasbin/issues/154

fix: FilteredAdapter cast is correctly casting to interface now

---

.github/workflows/maven-ci.yml
README.md

docs: Add github action badge.

---

src/main/java/org/casbin/jcasbin/model/Policy.java

docs: add policy description.

---

src/main/java/org/casbin/jcasbin/model/Model.java

Made all the changes that were asked in #161  .

fix: Removed repeated section in loadModel and loadModelFromText in Model.java

---

examples/rbac_with_hierarchy_policy_without_role.csv
src/main/java/org/casbin/jcasbin/rbac/DefaultRoleManager.java
src/test/java/org/casbin/jcasbin/main/SyncedRbacAPIUnitTest.java

fix: https://github.com/casbin/jcasbin/issues/162

fix: return empty list when name does not exist in getRoles function.

---

pom.xml

build: change the slf4j scope.

---

src/main/java/org/casbin/jcasbin/main/DistributedEnforcer.java

Just a small correction. Corrected description of distributed enforcer.

Corrected description of distributed enforcer

---

examples/priority_model_explicit.conf
examples/priority_policy_explicit.csv
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/model/Model.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

ideas:
- sort the policies by priority value when loading policies
- use binary insertion when adding a policy with priority value
Fix: https://github.com/casbin/jcasbin/issues/173

feat: add support for priority matching

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java

add the `getRoleManager` function in `CoreEnforcer.java`

fix: add the getRoleManager function

---

examples/priority_model_explicit.conf
examples/priority_policy_explicit.csv
src/main/java/org/casbin/jcasbin/model/Assertion.java
src/main/java/org/casbin/jcasbin/model/Model.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

fix: priority cannot be non first policy element

---

src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

fix: https://github.com/casbin/jcasbin/issues/187

fix: add the batchEnforce API.

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

feat: add support for dynamic matching

---

.github/workflows/maven-ci.yml

fix: use "github-actions" to send release notice

---

.github/workflows/maven-ci.yml

See: https://github.com/semantic-release/semantic-release/issues/1981

ci: upgrade Node.js version to 16

---

src/main/java/org/casbin/jcasbin/util/function/CustomFunction.java

fix: CustomFunction.replaceTargets replaces too much

---

src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

Fix: https://github.com/casbin/jcasbin/issues/212

fix:  the PatternSyntaxException for android

---

examples/in_op_sytanx.conf
src/main/java/org/casbin/jcasbin/util/Util.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java

fix: change 'in' op to 'include'

---

src/main/java/org/casbin/jcasbin/model/FunctionMap.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/function/KeyMatch5Func.java
src/test/java/org/casbin/jcasbin/main/BuiltInFunctionsUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

feat: add keyMatch5 for ignoring params in url

---

src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

fix: add cache for g function

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/ManagementEnforcer.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

fix: fix the cache for g function

---

src/main/java/org/casbin/jcasbin/effect/DefaultEffector.java
src/main/java/org/casbin/jcasbin/effect/DefaultStreamEffector.java
src/main/java/org/casbin/jcasbin/effect/DefaultStreamEffectorResult.java
src/main/java/org/casbin/jcasbin/effect/Effector.java
src/main/java/org/casbin/jcasbin/effect/StreamEffector.java
src/main/java/org/casbin/jcasbin/effect/StreamEffectorResult.java
src/main/java/org/casbin/jcasbin/exception/CasbinEffectorException.java
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java

Use stream effector instead of current effector, it can quickly return result.

feat: support stream effector

---

examples/multiple_policy_definitions_model.conf
examples/multiple_policy_definitions_policy.csv
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/util/EnforceContext.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/241

feat: support multiple request, policy, effect, matcher type

---

src/main/java/org/casbin/jcasbin/util/Util.java

Fix: https://github.com/casbin/jcasbin/issues/243

feat: support escape character in policy rule

---

pom.xml
src/main/java/org/casbin/jcasbin/main/Frontend.java
src/test/java/org/casbin/jcasbin/main/FrontendUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/247

feat: casbinJsGetPermissionForUser

---

pom.xml

fix: upgrade dependencies

---

src/main/java/org/casbin/jcasbin/model/Policy.java
src/main/java/org/casbin/jcasbin/util/Util.java

fix: Implemented a method which returned "true" without doing anything, used in Policy.java class

fix: Implemented arrayRemoveDuplicates

---

examples/rbac_with_multiple_policy_model.conf
examples/rbac_with_multiple_policy_policy.csv
src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/test/java/org/casbin/jcasbin/main/RbacAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/267

feat: allow permissions management to use additional p-types

---

examples/rbac_with_pattern_regex_policy.csv
src/main/java/org/casbin/jcasbin/rbac/DomainRoles.java
src/test/java/org/casbin/jcasbin/main/RbacAPIUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/270

fix: hasRole should return true if name equals, no matter what matchingFunc is used

---

src/test/java/org/casbin/jcasbin/main/RoleManagerUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

add unit tests for https://github.com/casbin/jcasbin/issues/261

test: add unit tests for DefaultRoleManager

---

src/main/java/org/casbin/jcasbin/persist/Helper.java

Improve index calculation on policy loading.

fix: Update helper for loading policies

---

src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java

Fix: https://github.com/casbin/jcasbin/issues/292
I reproduced the bug mentioned in the issue. But not sure the exact reason, the bug appeared after this pr https://github.com/casbin/jcasbin/pull/265, I compared the code and found it caused by hashmap, then made this modification and it did work.

fix: fix hashmap thread unsafe

---

src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/test/java/org/casbin/jcasbin/main/RbacAPIWithDomainsUnitTest.java
src/test/java/org/casbin/jcasbin/main/RbacAPIWithPatternMatchUnitTest.java
src/test/java/org/casbin/jcasbin/main/SyncedRbacAPIWithDomainsUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/295

feat: add getUsersForRoleInDomain()

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedEnforcer.java
src/main/java/org/casbin/jcasbin/util/Util.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/SyncedEnforcerUnitTest.java
src/test/java/org/casbin/jcasbin/main/TestUtil.java

Fix: https://github.com/casbin/jcasbin/issues/297

feat: support enforceEx

---

examples/priority_hierachy_policy.conf
examples/priority_hierachy_policy.csv
examples/subject_priority_model_with_domain.conf
examples/subject_priority_policy_with_domain.csv
src/main/java/org/casbin/jcasbin/effect/DefaultEffector.java
src/main/java/org/casbin/jcasbin/effect/DefaultStreamEffector.java
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/model/Model.java
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/301
Replace: https://github.com/casbin/jcasbin/pull/303

feat: Implement subject Priority in jcasbin

---

.github/workflows/maven-ci.yml

fix: update Node to 18 in CI maven-ci.yml

---

pom.xml
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/Enforcer.java
src/main/java/org/casbin/jcasbin/persist/file_adapter/FilteredAdapter.java

Fix: https://github.com/casbin/jcasbin/issues/264

feat: change aviator dependency to org.casbin.aviator.5.1.4-fix to support below Android 8.0 (API level 26)

---

examples/rbac_with_resource_roles_and_domain_model.conf
examples/rbac_with_resource_roles_and_domain_policy.csv
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/328
test: add rbac with resource roles and domain example

fix: add rbac with resource roles and domain example

---

src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/test/java/org/casbin/jcasbin/main/BuiltInFunctionsUnitTest.java

fix: https://github.com/casbin/jcasbin/issues/339

fix: update keyMatch2 for key2 == *

---

examples/keymatch_with_rbac_in_domain.conf
examples/keymatch_with_rbac_in_domain.csv
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java

ci: add KeyMatch to RBAC inheritance

---

pom.xml
src/main/java/org/casbin/jcasbin/log/DefaultLogger.java
src/main/java/org/casbin/jcasbin/log/LogUtil.java
src/main/java/org/casbin/jcasbin/log/Logger.java
src/main/java/org/casbin/jcasbin/log/mocks/MockLogger.java
src/test/java/org/casbin/jcasbin/main/ConfigTest.java
src/test/java/org/casbin/jcasbin/main/LogUtilTest.java

Part of: https://github.com/casbin/jcasbin/issues/367

feat: add DefaultLogger feature

---

examples/abac_not_using_policy_model.conf
examples/abac_rule_effect_policy.csv
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java

fix not using policy bug for enforcer and sync test case
part of #367

fix: fix not using policy bug for enforcer (testABACJsonRequest, testABACNotUsingPolicy)

---

examples/comment_model.conf
src/main/java/org/casbin/jcasbin/config/Config.java
src/test/java/org/casbin/jcasbin/main/ModelUnitTest.java

add "#",";" process for conf file and sync test case
part of #367

feat: support comment ("#",";") in model (testCommentModel)

---

pom.xml

Fix: https://github.com/casbin/jcasbin/issues/375

feat: Update com.github.seancfoley:ipaddress version

---

src/main/java/org/casbin/jcasbin/main/Frontend.java
src/test/java/org/casbin/jcasbin/main/FrontendUnitTest.java

add user interactions in casbinJsGetPermissionForUser method
Fix: https://github.com/casbin/jcasbin/issues/395

feat: add user interactions in casbinJsGetPermissionForUser method

---

pom.xml
src/main/java/org/casbin/jcasbin/cli/Client.java
src/test/java/org/casbin/jcasbin/main/ClientTest.java

feat: support CLI usage for jCasbin

---

src/main/java/org/casbin/jcasbin/util/Util.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java

feat: fix the comma separater bug

---

pom.xml

feat: fix pom.xml to fix CI

---

pom.xml

Fix: https://github.com/casbin/jcasbin/issues/426

feat: upgrade aviator dependency to latest v5.4.3

---

pom.xml
src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/main/DistributedEnforcer.java
src/main/java/org/casbin/jcasbin/model/Model.java
src/main/java/org/casbin/jcasbin/model/Policy.java
src/main/java/org/casbin/jcasbin/persist/Dispatcher.java
src/main/java/org/casbin/jcasbin/rbac/ConditionalRoleManager.java
src/main/java/org/casbin/jcasbin/rbac/DefaultRoleManager.java
src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
src/main/java/org/casbin/jcasbin/util/EnforceContext.java
src/main/java/org/casbin/jcasbin/util/Util.java
src/main/java/org/casbin/jcasbin/util/function/KeyMatch5Func.java

Fix Javadoc: Add missing descriptions and use correct escape characters
Fix: https://github.com/casbin/jcasbin/issues/429

feat: fix javadoc

---

src/main/java/org/casbin/jcasbin/exception/CasbinCacheException.java
src/main/java/org/casbin/jcasbin/main/CachedEnforcer.java
src/main/java/org/casbin/jcasbin/persist/cache/Cache.java
src/main/java/org/casbin/jcasbin/persist/cache/CacheItem.java
src/main/java/org/casbin/jcasbin/persist/cache/CacheableParam.java
src/main/java/org/casbin/jcasbin/persist/cache/DefaultCache.java
src/test/java/org/casbin/jcasbin/main/CachedEnforcerUnitTest.java

Synchronize CachedEnforcer related classes.
Fix: https://github.com/casbin/jcasbin/issues/434

feat: port CachedEnforcer API from Go to Java

---

src/main/java/org/casbin/jcasbin/main/CoreEnforcer.java
src/main/java/org/casbin/jcasbin/util/Util.java
src/test/java/org/casbin/jcasbin/main/AbacAPIUnitTest.java
src/test/java/org/casbin/jcasbin/main/UtilTest.java

feat: Revert "feat: fix the double quotes caused eval() bug"

---

src/main/java/org/casbin/jcasbin/main/CachedEnforcer.java
src/main/java/org/casbin/jcasbin/main/SyncedCachedEnforcer.java
src/main/java/org/casbin/jcasbin/persist/cache/Cache.java
src/main/java/org/casbin/jcasbin/persist/cache/DefaultCache.java
src/test/java/org/casbin/jcasbin/main/CachedEnforcerUnitTest.java

Fix: https://github.com/casbin/jcasbin/issues/456

feat: fix CachedEnforcer bug that false result was not cached
